import { NBATeam } from './types';

export const NBA_TEAMS: NBATeam[] = [
  { id: 1, abbreviation: "ATL", city: "Atlanta", conference: "East", division: "Southeast", full_name: "Atlanta Hawks", name: "Hawks", wins: 36, losses: 46, color: "#E03A3E", secondaryColor: "#C1D32F" },
  { id: 2, abbreviation: "BOS", city: "Boston", conference: "East", division: "Atlantic", full_name: "Boston Celtics", name: "Celtics", wins: 64, losses: 18, color: "#007A33", secondaryColor: "#BA9653" },
  { id: 3, abbreviation: "BKN", city: "Brooklyn", conference: "East", division: "Atlantic", full_name: "Brooklyn Nets", name: "Nets", wins: 32, losses: 50, color: "#000000", secondaryColor: "#FFFFFF" },
  { id: 4, abbreviation: "CHA", city: "Charlotte", conference: "East", division: "Southeast", full_name: "Charlotte Hornets", name: "Hornets", wins: 21, losses: 61, color: "#1D1160", secondaryColor: "#00788C" },
  { id: 5, abbreviation: "CHI", city: "Chicago", conference: "East", division: "Central", full_name: "Chicago Bulls", name: "Bulls", wins: 39, losses: 43, color: "#CE1141", secondaryColor: "#000000" },
  { id: 6, abbreviation: "CLE", city: "Cleveland", conference: "East", division: "Central", full_name: "Cleveland Cavaliers", name: "Cavaliers", wins: 48, losses: 34, color: "#860038", secondaryColor: "#FDBB30" },
  { id: 7, abbreviation: "DAL", city: "Dallas", conference: "West", division: "Southwest", full_name: "Dallas Mavericks", name: "Mavericks", wins: 50, losses: 32, color: "#00538C", secondaryColor: "#002B5E" },
  { id: 8, abbreviation: "DEN", city: "Denver", conference: "West", division: "Northwest", full_name: "Denver Nuggets", name: "Nuggets", wins: 57, losses: 25, color: "#0E2240", secondaryColor: "#FEC524" },
  { id: 9, abbreviation: "DET", city: "Detroit", conference: "East", division: "Central", full_name: "Detroit Pistons", name: "Pistons", wins: 14, losses: 68, color: "#C8102E", secondaryColor: "#1D42BA" },
  { id: 10, abbreviation: "GSW", city: "Golden State", conference: "West", division: "Pacific", full_name: "Golden State Warriors", name: "Warriors", wins: 46, losses: 36, color: "#1D428A", secondaryColor: "#FFC72C" },
  { id: 11, abbreviation: "HOU", city: "Houston", conference: "West", division: "Southwest", full_name: "Houston Rockets", name: "Rockets", wins: 41, losses: 41, color: "#CE1141", secondaryColor: "#000000" },
  { id: 12, abbreviation: "IND", city: "Indiana", conference: "East", division: "Central", full_name: "Indiana Pacers", name: "Pacers", wins: 47, losses: 35, color: "#002D62", secondaryColor: "#FDBB30" },
  { id: 13, abbreviation: "LAC", city: "Los Angeles", conference: "West", division: "Pacific", full_name: "LA Clippers", name: "Clippers", wins: 51, losses: 31, color: "#C8102E", secondaryColor: "#1D428A" },
  { id: 14, abbreviation: "LAL", city: "Los Angeles", conference: "West", division: "Pacific", full_name: "Los Angeles Lakers", name: "Lakers", wins: 47, losses: 35, color: "#552583", secondaryColor: "#FDB927" },
  { id: 15, abbreviation: "MEM", city: "Memphis", conference: "West", division: "Southwest", full_name: "Memphis Grizzlies", name: "Grizzlies", wins: 27, losses: 55, color: "#5D76A9", secondaryColor: "#12173F" },
  { id: 16, abbreviation: "MIA", city: "Miami", conference: "East", division: "Southeast", full_name: "Miami Heat", name: "Heat", wins: 46, losses: 36, color: "#98002E", secondaryColor: "#F9A01B" },
  { id: 17, abbreviation: "MIL", city: "Milwaukee", conference: "East", division: "Central", full_name: "Milwaukee Bucks", name: "Bucks", wins: 49, losses: 33, color: "#00471B", secondaryColor: "#EEE1C6" },
  { id: 18, abbreviation: "MIN", city: "Minnesota", conference: "West", division: "Northwest", full_name: "Minnesota Timberwolves", name: "Timberwolves", wins: 56, losses: 26, color: "#0C2340", secondaryColor: "#236192" },
  { id: 19, abbreviation: "NOP", city: "New Orleans", conference: "West", division: "Southwest", full_name: "New Orleans Pelicans", name: "Pelicans", wins: 49, losses: 33, color: "#0C2340", secondaryColor: "#C8102E" },
  { id: 20, abbreviation: "NYK", city: "New York", conference: "East", division: "Atlantic", full_name: "New York Knicks", name: "Knicks", wins: 50, losses: 32, color: "#006BB6", secondaryColor: "#F58426" },
  { id: 21, abbreviation: "OKC", city: "Oklahoma City", conference: "West", division: "Northwest", full_name: "Oklahoma City Thunder", name: "Thunder", wins: 57, losses: 25, color: "#007AC1", secondaryColor: "#EF6100" },
  { id: 22, abbreviation: "ORL", city: "Orlando", conference: "East", division: "Southeast", full_name: "Orlando Magic", name: "Magic", wins: 47, losses: 35, color: "#0077C0", secondaryColor: "#C4CED4" },
  { id: 23, abbreviation: "PHI", city: "Philadelphia", conference: "East", division: "Atlantic", full_name: "Philadelphia 76ers", name: "76ers", wins: 47, losses: 35, color: "#006BB6", secondaryColor: "#ED174C" },
  { id: 24, abbreviation: "PHX", city: "Phoenix", conference: "West", division: "Pacific", full_name: "Phoenix Suns", name: "Suns", wins: 49, losses: 33, color: "#1D1160", secondaryColor: "#E56020" },
  { id: 25, abbreviation: "POR", city: "Portland", conference: "West", division: "Northwest", full_name: "Portland Trail Blazers", name: "Trail Blazers", wins: 21, losses: 61, color: "#E03A3E", secondaryColor: "#000000" },
  { id: 26, abbreviation: "SAC", city: "Sacramento", conference: "West", division: "Pacific", full_name: "Sacramento Kings", name: "Kings", wins: 46, losses: 36, color: "#5A2D81", secondaryColor: "#63727A" },
  { id: 27, abbreviation: "SAS", city: "San Antonio", conference: "West", division: "Southwest", full_name: "San Antonio Spurs", name: "Spurs", wins: 22, losses: 60, color: "#C4CED4", secondaryColor: "#000000" },
  { id: 28, abbreviation: "TOR", city: "Toronto", conference: "East", division: "Atlantic", full_name: "Toronto Raptors", name: "Raptors", wins: 25, losses: 57, color: "#CE1141", secondaryColor: "#000000" },
  { id: 29, abbreviation: "UTA", city: "Utah", conference: "West", division: "Northwest", full_name: "Utah Jazz", name: "Jazz", wins: 31, losses: 51, color: "#002B5C", secondaryColor: "#00471B" },
  { id: 30, abbreviation: "WAS", city: "Washington", conference: "East", division: "Southeast", full_name: "Washington Wizards", name: "Wizards", wins: 15, losses: 67, color: "#002B5C", secondaryColor: "#E31837" },
];
